### ISSUE TITLE
Error writing transmitter challenge: timeout

### ISSUE THREAD

**Issue by danyocom** [LoopKit/xDripG5#49]
I am trying to get xDripG5 working with PassiveMode turned off (Dexcom App is uninstalled). However, I am getting the error "Error writing transmitter challenge: timeout"  Any ideas? Is there any 'tricks/configurations' to getting xDripG5 communication working as a "standalone" app? (No dexcom app).

**Comment by pi4ohhi7** [comment]
Might be related to the pull request I just opened. I think authentication (which is only relevant when PassiveMode is off) was broken.

**Comment by ps2** [comment]
The code has changed a lot since this was filed. Going to close; if there are still issues, please reopen them with steps to reproduce using current code.
