### ISSUE TITLE
CocoaPods repo seems to be limited to version 0.6

### ISSUE THREAD

**Issue by aranasaurus** [LoopKit/xDripG5#50]
Is that on purpose? I had to link directly to this repo to get Swift 3 support working for a friend:  https://github.com/hanneshapke/glucose-badge/pull/1

[cocoapods.org](https://cocoapods.org/pods/xDripG5)

**Comment by ps2** [comment]
I don't think that's on purpose.  Not being a cocoapods user myself, I'm not sure what is needed to support newer versions.  Please submit a PR if you have some changes for cocoapod support.

**Comment by aranasaurus** [comment]
[This page](https://guides.cocoapods.org/making/specs-and-specs-repo.html) in their docs says "only authoritative versions can be used". I think that means you (or whoever uploaded it the first time) has to do it. I think you just have to run the commands in the Updating a spec section. Your podspec is already up to date, as evidenced by it just working when I point my podfile directly to your repo.

**Comment by aranasaurus** [comment]
Oh I see the problem now. At version 0.6.0 you started prepending your version tags with a "v" and the Podspec is set to look for a tag that is just the version number, without the v.

**Comment by aranasaurus** [comment]
so either the tags need to be changed to not have that v, or you need to add the v to the podspec.

Changing this line in the podspec:
```  s.source           = { :git => "https://github.com/LoopKit/xDripG5.git", :tag => "v" + s.version.to_s }```

makes `pod spec lint` pass on my local clone.
