### ISSUE TITLE
"Encryption is insufficient" error when PassiveMode is disabled

### ISSUE THREAD

**Issue by pi4ohhi7** [LoopKit/xDripG5#55]
Seems that with my newest transmitter, every request that gets sent to the transmitter results in the error "Encryption is insufficient". Had to modify xDripG5 to get the error information (specifically the error handling at the end of writeValueAndWait in BluetoothManager); on the stock main branch it just shows up as a timeout.

**Comment by ps2** [comment]
Would you be able to submit a PR that catches these kinds of errors and reports them to the delegate? Lookig at your other PR now.

**Comment by pi4ohhi7** [comment]
Sure, can do, though it may take me a bit to figure out how to fix it (I just added a bunch of print statements to find it).

The problem is BluetoothManager doesn't correctly handle errors passed to

`func peripheral(_ peripheral: CBPeripheral, didWriteValueFor characteristic: CBCharacteristic, error: Error?)`

An error passed here does modify operationError, but it doesn't bypass the 2 second wait time for a reply. When the requesting function (e.g. writeValueAndWait) stops waiting on operationLock it checks for a timeout before an error:

`        if !signaled {
            throw BluetoothManagerError.timeout
        } else if let operationError = operationError {
            throw BluetoothManagerError.cbPeripheralError(operationError)
        }
`

**Comment by pi4ohhi7** [comment]
With #56, error passed to the delegate after xDripG5 writes TransmitterTimeTxMessage is as follows:

`controlError("Error writing time request: cbPeripheralError(Error Domain=CBATTErrorDomain Code=15 \"Encryption is insufficient.\" UserInfo={NSLocalizedDescription=Encryption is insufficient.})")`

**Comment by pi4ohhi7** [comment]
Made some progress on this (#57). Was browsing [NightscoutFoundation/xDrip](https://github.com/NightscoutFoundation/xDrip.git) and noticed that they had an option to do the full auth every time. Doing that seems to eliminate the "Encryption is insufficient" problem, but there's some caveats.

- the first time the transmitter connects it seems to timeout in auth somewhere
- every session with the transmitter the final disconnect tx message seems to be timing out
- every session with the transmitter I see `[CoreBluetooth] WARNING: Unknown error: 913` in the console

I also wonder if auth-ing every time with the transmitter could reduce transmitter battery life.

**Comment by ps2** [comment]
There is better support for standalone mode in dev now.  Thanks @thebookins
