### ISSUE TITLE
fails to connect after restoring peripheral from state

### ISSUE THREAD

**Issue by thebookins** [LoopKit/xDripG5#75]
I have noticed at times that when I run the example app with the same transmitter ID as a previous session, the app fails to scan or connect. Rather than seeing the expected log messages (`Scanning for peripherals` or `Reconnecting to known peripheral ... in 180.0 s`) I just see the message `Restoring peripheral from state ...`. This is on latest dev and iOS 11.2.5.

**Comment by ps2** [comment]
This is intended behavior; state restoration is spinning up correctly.  Are you actually seeing issues if you wait for up to the 5 minute cycle?

**Comment by thebookins** [comment]
Yeah, I’ve tried waiting for several 5 minute cycles and it never connects.

**Comment by thebookins** [comment]
I investigated a bit further, and found that when the peripheral is restored from state, the `CBPeripheralState` is `.connecting`. So it falls over at [this guard statement](https://github.com/LoopKit/xDripG5/blob/49189d7b005e9a56167bbf4d5b5b7f06d2a0a4bd/xDripG5/BluetoothManager.swift#L99) and we don't end up scanning.

I tried disconnecting from the peripheral in `deinit` (i.e. like before #72) but no difference. I'm not sure what the best solution is; would it work to add `.connecting` to the list of acceptable states?

**Comment by ps2** [comment]
Guessing in the dark: there could be an issue where a restored CBPeripheral has a state of .connecting but that connect request needs to be re-instated. This sounds like a potential Core Bluetooth bug.

A fix could be to allow BluetoothManager to re-ask a peripheral in the .connecting state to connect; I can't imagine any negative consequences of that.

See https://github.com/LoopKit/xDripG5/tree/allow-reconnect-when-connecting for a diff that tweaks the guard statement slightly for that case.

**Comment by thebookins** [comment]
Should do the trick. Thanks.

**Comment by thebookins** [comment]
Haven't had any issues since #82, which implements the new guard statement. Thanks. Closing.
