### ISSUE TITLE
Support backfilling glucose values

### ISSUE THREAD

**Issue by trixing** [LoopKit/xDripG5#79]
Newer transmitters when longer out of range will do a bulk reply of past glucose values.  This does not seem to be interpreted by xDripG5 and will only interpret the single next value afaict.  It would be nice to backfill this data by calling the callback multiple times to the listening app.  Not sure if this should rather go into the Loop/Loop issue tracker as it could in theory pull that data from dexcom-share.

**Comment by ps2** [comment]
Fixed with #82
