### ISSUE TITLE
won't compile for iOS 10

### ISSUE THREAD

**Issue by thebookins** [LoopKit/xDripG5#80]
For some reason the availability check [here](https://github.com/LoopKit/xDripG5/blob/b9c264af7402fe645616f0a6d1e38624da59f7fb/xDripG5/BluetoothManager.swift#L104-L106) doesn't protect the code inside, and the compiler complains with `dyld: Symbol not found: _CBConnectPeripheralOptionStartDelayKey`, when compiling for iOS 10.x.

**Comment by ps2** [comment]
"Compile for iOS 10" means iOS 10 is the IPHONEOS_DEPLOYMENT_TARGET, but SDKROOT is "iphoneos" (or, current).
None of the LoopKit projects support using Xcode versions earlier than the most current major version, or using an SDKROOT that's anything earlier than the most current major version of iOS. All the LoopKit projects currently have their deployment target set to iOS 10, including xDripG5.

**Comment by thebookins** [comment]
Perhaps I was unclear. I'm using the latest version of Xcode, and haven't changed any of the deployment targets. I can build and run on a phone running iOS 11, but cannot build and run on a phone running iOS 10. I assumed that the compiler would ignore whatever code was protected by `if #available(iOS 11.2, watchOS 4.1, *), delay > 0 { }` for the iOS 10 case, but it complains about `CBConnectPeripheralOptionStartDelayKey`.

**Comment by thebookins** [comment]
Yes, it's a linking error; not a compile error.

**Comment by ps2** [comment]
Fixed with #86
